### ISSUE TITLE
data-anchor-target

### ISSUE THREAD

**Issue by Prinzhorn** [Prinzhorn/skrollr-stylesheets#10]
There's no way to set `data-anchor-target` (neither `data-smooth-scroll` or others).

I don't know how the syntax should look like or if this should be added at all.

**Comment by davydkov** [comment]
This works for me:

``` css
@-skrollr-keyframes animation-name {
  anchor-target {.welcome}
  top {
    opacity:0
  }
}
```

Check out source - it just adds everything from css as "data-" attributes to elements

**Comment by Prinzhorn** [comment]
LOL, you're right. I didn't thought about that. It's not tested though. It will probably break with more complex selectors.

But that's by far the most elegant solution.

**Comment by marcorivm** [comment]
Sass doesn't like that syntax :(
Maybe:
anchor-target { value: '.welcome'; }

so Sass thinks is valid?

**Comment by Prinzhorn** [comment]
> Maybe:
> anchor-target { value: '.welcome'; }

It does sound reasonable, but not easy to integrate with the current code. I'm not a SASS expert, maybe there's a workaround with string interpolation or something like that.

**Comment by jackblackCH** [comment]
the less parser doesn't like it either of course. i will create separate animations.css file and exclude them in less parser.

**Comment by sherwinyu** [comment]
@jackblackCH Could you go into more detail? I'm encountering this issue right now -- it'd be great to include the anchor-target in the skrollr style sheet and still be able to use sass/less. Did you find a workaround?

**Comment by Prinzhorn** [comment]
``` css
#foo {
    -skrollr-anchor-target: '#bar';
}
```

https://github.com/Prinzhorn/skrollr-stylesheets#attributes

**Comment by sherwinyu** [comment]
:+1: Thanks! Skrollr is awesome

**Comment by jackblackCH** [comment]
Thanks for fast answer, Alex!
