### ISSUE TITLE
Colors in stylesheets

### ISSUE THREAD

**Issue by mafrost** [Prinzhorn/skrollr-stylesheets#11]
Maybe this has more to do with the SASS to CSS converter but for me, all RGB values are converted to HEX which gives an error when they are to be animated in Skrollr. The problem goes away when using RGBA with Alpha < 1

Have anyone else encountered this problem? 

.PS. This plugin makes Skrollr even better .DS.

**Comment by Prinzhorn** [comment]
skrollr doesn't support hex colors. I didn't knew that SASS can't be forced to output `rgb` colors.

For now you need to use your workaround, i.e. set alpha to something like `0.99999`.

**Comment by mafrost** [comment]
Ok, thanks!

**Comment by marcorivm** [comment]
:-1: for SASS  ran into this problem today. Quick fix:

```
@function rgb-color($r,$g,$b) {
  @return unquote('rgb(' + $r + ',' + $g + ',' + $b + ')');
}     
background-color: rgb-color(234,233,230)
```

**Comment by Prinzhorn** [comment]
Closing this. Someone created https://github.com/FezVrasta/skrollr-colors which you should include after skrollr-stylesheets and have hex colors working.
