### ISSUE TITLE
Failing tests

### ISSUE THREAD

**Issue by Prinzhorn** [Prinzhorn/skrollr-stylesheets#14]
Moved from #10, originally by @dsteplight

I'm not sure if this is related but  when I run your test/index.html file  the two tests fail in Chome, Safari and FF. Skrollr gives me a lot of flexibility and I love it but I want to do different animations settings for different devices. 

Skrollr Stylesheets looked like the answer and the syntax made sense, but i'm not seeing the desired results.  I included a screen shot of the test results. 
![screen shot 2013-05-16 at 3 25 08 pm](https://f.cloud.github.com/assets/816168/514671/673b8c02-be5e-11e2-9fcc-1d2f3c4eba1d.png)

What's the best method for creating different animation settings for different mobile devices?

**Comment by Prinzhorn** [comment]
What errors does the console show? Those are not just failing tests, but errors in the test run (it should be 16 tests not 2).

**Comment by dsteplight** [comment]
Regarding these tests it looks like /test/style-media-ignore.css is missing. When I look in the directory I see style-ignore.css style.css instead. This has nothing to do with my original problem I posted about but this may be the reason why these tests are failing.

**Comment by Prinzhorn** [comment]
Ahhh, I missed a `git add` ;-)

**Comment by Prinzhorn** [comment]
What was your original problem? Please open a separate issue.
