### ISSUE TITLE
Skrollr Animations Not Working With External Stylesheets

### ISSUE THREAD

**Issue by dsteplight** [Prinzhorn/skrollr-stylesheets#15]
I have an external style sheet like this  (I just added more of my own stuff to your stylesheet for now. I like lesscss but I didn't work in the less files)

 12         <link href="examples/main.css" rel="stylesheet" type="text/css" media="only screen" data-skrollr-stylesheet /> wich includes this css

110 #bg2 {
111   height:100%;
112   z-index: -49;
113   background-image: url("../images/scene-1-bg-large.png");
114   background-repeat:no-repeat;
115   background-color: #000000;
116   -skrollr-animation-name:background1;
117 }
118 @-skrollr-keyframes background1 {
119     0 {
120         display:block;background-position:0% 0px;top:0px;
121     }
122     2000 {
123         background-position:0% -164px;top: -100%;
124     }
125 }

I'm loading my javascript  like this 
 22       <script type="text/javascript" src="scripts/skrollr.stylesheets.min.js"></script>

and I have a div like this 

 29                 <div id="bg2"> </div>

How come I can't see my background anymore when I use skrollr css animation? Things work fine when I have everything inline? I want to be able to animation differently on different devices. I also want to load different background images based on media queries. I know. I can't put media queries in my style sheets but I was hoping to load different style sheets using media queries.

For now I didn't use any media queries. I just want to see my change work on screen devices and then I will get more specific with which device.

**Comment by Prinzhorn** [comment]
Please paste your code indented and as code. Read more about formatting here https://help.github.com/articles/github-flavored-markdown#syntax-highlighting

**Comment by Prinzhorn** [comment]
Or even better, fork the skrollr repo, make changes, push them and link to your fork. I can then just clone it and check it out without having to set up everything on my own (add files, apply changes, etc.).

**Comment by dsteplight** [comment]
I have to get a demo working by tomorrow morning. I may not have time to play with the skrollr repo since I have to focus on my current demo. I'll dig deeper into it this weekend though.

**Comment by ghost** [comment]
I have a similar issue. I made it work by modifying (or adding) last keyword 'bottom' instead of number value. Also it doesn't work if you put a comment inside.

I'm still new to git but I'll check the code and see if I can contribute with a fix.

**Comment by Prinzhorn** [comment]
I can't help you without code. I need a breaking case in order to create a test and then fix it.

**Comment by Prinzhorn** [comment]
Closing because inactive.
