### ISSUE TITLE
Skrollr Stylesheets not working in IE8

### ISSUE THREAD

**Issue by SILENTRUN** [Prinzhorn/skrollr-stylesheets#16]
After upgrading to skrollr 6.4, skrollr stylesheets 0.0.3 stopped working in IE 8. Reverting back to skrollr 5.14 fixed the issue using skrollr stylesheets 0.0.3.

**Comment by Prinzhorn** [comment]
Hm, this doesn't make much sense, because skrollr-stylesheets doesn't use skrollr.

Did you read the [changelog](https://github.com/Prinzhorn/skrollr#060-2013-05-18) for 0.6?

**Comment by Prinzhorn** [comment]
Closing because inactive.
