### ISSUE TITLE
Add initialization

### ISSUE THREAD

**Issue by G-4** [Prinzhorn/skrollr-stylesheets#19]
So that, under certain conditions, to enable parsing of animation styles.

**Comment by Prinzhorn** [comment]
I'm not sure I understand what you want. Could you please provide more details?

**Comment by G-4** [comment]
I mean
not only connect js file skrollr.stylesheets.min.js
and even cause the initialization as skrollr.init ()

I need to disable the scroll on mobile devices, but that worked skrollr.menu
maybe there is a way to implement?

**Comment by Prinzhorn** [comment]
If you're not calling `skrollr.init`, nothing will happen. skrollr-stylesheets doesn't do anything "visible" to the user.

**Comment by G-4** [comment]
if i not calling `skrollr.init` , how work `skrollr.menu`?

``` javascript
var s = skrollr.init();
skrollr.menu.init(s, {
    animate: true, 
});
```

**Comment by Prinzhorn** [comment]
> if i not calling skrollr.init , how work skrollr.menu?

huh? You can't. This is the skrollr-stylesheets repo. I'm not sure what you want.

**Comment by G-4** [comment]
I need to disable the `skrollr` effect only mobile devices, but worked `skrollr.menu`

**Comment by Prinzhorn** [comment]
I'm sorry if I couldn't help. It's just that your sentences are very hard to understand, probably because you're non-native speaker (just like me). The last sentence "but worked skrollr.menu" just doesn't make sense to me.

**Comment by G-4** [comment]
Excuse me for my english.
See this code you will understand

``` html
<head>
    <link rel="stylesheet" type="text/css" href="animation.css" data-skrollr-stylesheet />
</head>
<body>
    <a id="link" href="#section-about" data-menu-top="600">About</a>
    ...
    <div id="foo">WOOOT</div>
    ...
    <div id="section-about">text about</div>

    <script src="skrollr.min.js"></script>
    <script src="skrollr.menu.min.js"></script>
    <script src="skrollr.stylesheets.min.js"></script>

    <script>
        var s = skrollr.init(/*other stuff*/);
        skrollr.menu.init(s, {
            animate: true
        });
    </script>
</body>
```

animation.css

``` css
#foo {
    -skrollr-animation-name:animation1;
}

@-skrollr-keyframes animation1 {

    0 {
       background-color:rgb(0,0,255);
    }

    500 {
       background-color:rgb(255,0,0);  
    }
}
```

I want animation (change color) `<div id="foo">WOOT</div>` and animation menu `#link`  for desktop device.
For mobile device only animation menu.
See table

```
     | decktop | mobile |
-------------------------
#foo |   yes   |    no  |
-------------------------
#link|   yes   |   yes  |
```

how to do it?
Thanks for the help

**Comment by Prinzhorn** [comment]
Now I understand. Code is the universal language ;-)

Multiple options (possibly more than the three listed)

## 1. Use the `media` attribute on the stylesheet

``` html
<link media="only screen and (min-width: 800px)" rel="stylesheet" type="text/css" href="animation.css" data-skrollr-stylesheet />
```

## 2. Add this to your CSS

``` CSS
.skrollr-mobile #foo {
    background-color:rgba(0,0,255) !important;
}
```

## 3. Conditionally include the stylesheet or skrollr-stylesheets

``` js
if(!/Android|iPhone|iPad|iPod|BlackBerry|Windows Phone/i).test(navigator.userAgent || navigator.vendor || window.opera) {
    document.write('add stylesheet/javascript <link> or <script> here');
}
```

**Comment by G-4** [comment]
The listed two `!important;` it's very good.
Thanks for the help. Good luck to you.
