### ISSUE TITLE
LESS support

### ISSUE THREAD

**Issue by Prinzhorn** [Prinzhorn/skrollr-stylesheets#20]
Check to see if there are any issues with LESS (e.g. because of the -skrollr prefix). Document the results.

**Comment by m9dfukc** [comment]
Hey, 

LESS seems to work quite well, except for the easing functions.

for example:

``` css
top {
    opacity[cubic]: 0;
}
```

will generate an error as this is non valid LESS code. SASS will probably face the same issues?! 
All the other stuff including variable and dynamic function naming magic works fine.

**Comment by Prinzhorn** [comment]
Thanks for trying. Check #21 and see if something similar is available for LESS.

**Comment by danielskapunk** [comment]
Cant animate colors.
When trying to animate colors LESS compiler converts rgb colors to hex and ruins the animation.
The only way that I have find to avoid conversion is to use rgba with an alpha different to 1.0.

**Comment by Prinzhorn** [comment]
> Cant animate colors.
> When trying to animate colors LESS compiler converts rgb colors to hex and ruins the animation.
> The only way that I have find to avoid conversion is to use rgba with an alpha different to 1.0.

Same for SASS https://github.com/Prinzhorn/skrollr-stylesheets/issues/11

You can use literals though I guess `color:~"rgba(0,255,127)";`

**Comment by danielskapunk** [comment]
Thanks! That does the trick.

```
  o   o
    O  o
 o_/|\_,
    |
```

**Comment by roblovato** [comment]
How exactly do I get this to work with LESS? I've got everything set up correctly (tried the link to .css file & it works as expected), but when I use LESS, I get this parse error:
lessc fatal error:
parse error: failed at `0

Using this example
#foo {
    -skrollr-animation-name:animation1;
}

@-skrollr-keyframes animation1 {
    0 {
        left:100%;
    }...

**Comment by Prinzhorn** [comment]
Can't reproduce, maybe you should post your **actual** code.

This works for me

``` css
#foo {
    -skrollr-animation-name:animation1;
}

@-skrollr-keyframes animation1 {
    0 {
        left:100%;
    }
}
```

**Comment by roblovato** [comment]
My actual code

nav {
    -skrollr-animation-name: animation1;
}

@-skrollr-keyframes animation1 {

```
0 {
    height: 130px;
}

100 {
    height: 50px;
}
```

}

Updating our LESS php complier fixed the parse error, but still not seeing any effects on the elements with this code.

**Comment by Prinzhorn** [comment]
> Updating our LESS php complier fixed the parse error, but still not seeing any effects on the elements with this code.

this is likely an integration issue, not just the stylesheet you've posted.

**Comment by roblovato** [comment]
I decided to not bother with LESS and just create a separate css file for skrollr, using a link and data-skrollr-stylesheet attribute. Everything is working now with one exception. Our site is built using Knockout framework and the skrollr css doesn't get applied to dom elements inside Knockout templates using <script type="text/html" id="home_template"> tags. Is there a way to init skrollr.stylesheets using the Knockout template afterRender function?

**Comment by Prinzhorn** [comment]
> the skrollr css doesn't get applied to dom elements inside Knockout templates using

https://github.com/Prinzhorn/skrollr-stylesheets#limitations
