### ISSUE TITLE
Specifying an easing function while using SASS won't compile

### ISSUE THREAD

**Issue by interstateone** [Prinzhorn/skrollr-stylesheets#21]
I'm wondering if you have any ideas on best practices for specifying easing functions with SASS. e.g. color[swing]:rgb(0,0,0); will throw an error with a SASS compiler. A quick fix is to wrap the ease name in a literal string interpolation like: color#{"[swing]"}:rgb(0,0,0); but that's kind of ugly. I'm more familiar with LESS so perhaps I'm missing a feature that would allow this. Maybe worth a mention in the README?

Edit: I've also found that SASS likes to change the text format of colors (swapping rgba(0,0,0,1) for black, [issue here](https://github.com/nex3/sass/issues/363)) so you also need to wrap those in an interpolation so the values can be... uh... interpolated. :)

**Comment by Prinzhorn** [comment]
Too bad. I feared that this will break some things, because it's non-standard syntax. From the top of my head I don't know a nicer workaround.

Maybe we find an alternative syntax which skrollr core could support.

Regarding colors see https://github.com/Prinzhorn/skrollr-stylesheets/issues/11 . Let's hope this will be fixed in SASS.

**Comment by interstateone** [comment]
`opacity: 0 easing("swing");` compiles properly, and perhaps near [line 124](https://github.com/Prinzhorn/skrollr-stylesheets/blob/master/src/skrollr.stylesheets.js#L124) a substitution could be made if necessary to change it to look like `opacity[swing]: 0;` with something like `easing\("([\w-]*)` to capture the ease function name.

I'd be interested in submitting a pull request if we can come to a conclusion on the syntax first.

**Comment by Prinzhorn** [comment]
Given that it's more to type than `opacity#{"[swing]"}: 0;` what's the benefit? I mean the workaround is not pretty, but it's just 5 more characters and I'm not sure if I want code which is only necessary for SASS.

**Comment by interstateone** [comment]
You're right, not worth it to just support SASS. Would you accept a pull request that adds an easing example in the SASS section of the readme?

**Comment by Prinzhorn** [comment]
Sure.
