### ISSUE TITLE
IE8 issue with document.querySelectorAll(selectors[selectorIndex][0]);

### ISSUE THREAD

**Issue by annez** [Prinzhorn/skrollr-stylesheets#22]
Just tried and tested this on IE8 and I get the following error:

"Invalid argument"

Referring to the line

`elements = document.querySelectorAll(selectors[selectorIndex][0]);`

The stylesheets are external and using the latest version of Skrollr (although am aware that they are independent of each other).

**Comment by Prinzhorn** [comment]
it would be great if you could post what `selectors[selectorIndex][0]` is at that point.

**Comment by annez** [comment]
Ah, it's because I was using an nth-child selector that it failed. Makes sense. I've reverted to using classes and it works fine.

**Comment by Prinzhorn** [comment]
great!
