### ISSUE TITLE
skrollr-stylesheets not working

### ISSUE THREAD

**Issue by trophystudio** [Prinzhorn/skrollr-stylesheets#25]
Have been working with skrollr successfully for some time, tried to set up skrollr-stylesheets to handle the external stylesheets/media attributes as per the documentation, but it doesnt seem to work???

Link to code;

view-source:http://urbanplatform.co.uk/skrollr-stylesheets-master/skrollr.html

**Comment by Prinzhorn** [comment]
I updated the documentation https://github.com/Prinzhorn/skrollr-stylesheets#the-script

**Comment by trophystudio** [comment]
Working perfect now thanks
