### ISSUE TITLE
CSS comments not respected

### ISSUE THREAD

**Issue by michaelfillier** [Prinzhorn/skrollr-stylesheets#26]
I am attempting to disable some animations by commenting out the `-skrollr-animation-name` property, but skrollr-stylesheets applies the animation anyways.

Is this behaviour to be expected? As it stands, to disable an animation I need to delete the `-skrollr-animation-name` property entirely.

**Comment by Prinzhorn** [comment]
> When I say "parsing" I mean it's using regular expressions. Thus you should avoid doing funky stuff inside your CSS files (actually, comments at the wrong place could break the current version).

https://github.com/Prinzhorn/skrollr-stylesheets#documentation

For now I suggest you use a preprocessor which strips the comments (you should do that for production anyway). E.g. https://github.com/GoalSmashers/clean-css

**Comment by michaelfillier** [comment]
I understand, I guess it never hurts to fully read the documentation :). Thanks for the quick reply.
