### ISSUE TITLE
SASS problems

### ISSUE THREAD

**Issue by gl03** [Prinzhorn/skrollr-stylesheets#27]
Hi, skrollr(-stylesheets) is great, but i can't seem to get the SASS support to work. 

Would you mind clearing up its basic usage in the README, or point to a working example?

if i define a SASS variable, say:

```
$count_begin: 0;
```

before

```
#count1 { -skrollr-animation-name:count1; }
```

i get a "SYNTAX_ERR: DOM Exception 12: An invalid or illegal string was specified."

if I define it after, it is ignored. 

does the filetype need to be SASS instead of CSS? am i missing anything else?

**Comment by Prinzhorn** [comment]
You understood this wrong. You need to compile it to CSS first. The documentation just says how awesome it is to use SASS, because it makes it so much easier to set the animations.

**Comment by gl03** [comment]
ah, got you! thanks for setting me straight.
