### ISSUE TITLE
package.json

### ISSUE THREAD

**Issue by jamieGee** [Prinzhorn/skrollr-stylesheets#31]
We're using an automated build process to include skrollr-stylesheets which looks to have pointed out an inconsistency in the file names for the minified js file. 

The package.json lists the main file as "dist/skrollr-stylesheets.min.js" but the file is actually named "dist/skrollr.stylesheets.min.js". If you could update either the file name for the package.json that would be great. Thanks.

**Comment by Prinzhorn** [comment]
Thanks.

Why not create a PR next time?
