### ISSUE TITLE
CSS syntax needed by skrollr-stylesheets is not standard

### ISSUE THREAD

**Issue by giladgo** [Prinzhorn/skrollr-stylesheets#33]
Hey,

If I understood correctly, skrollr-stylesheets requires css in the form of `x[y]: blah`, for example:
`elem[transform]: transform3d(...)`

The problem with this is that, when sass wants to validate the outputted CSS (for example, for when you precompile assets in a Rails production environment), the validation fails.

Any way around this?

Thanks

**Comment by Prinzhorn** [comment]
https://github.com/Prinzhorn/skrollr-stylesheets/issues/21

https://github.com/Prinzhorn/skrollr-stylesheets#sass

> opacity#{"[swing]"}: 0.0;
