### ISSUE TITLE
Stylus integration

### ISSUE THREAD

**Issue by madsviktor** [Prinzhorn/skrollr-stylesheets#34]
I having trouble integrating with Stylus. I'm having trouble when trying to compile with "dynamic constants".

Error:

```
26| @-skrollr-keyframes intro {
>>  > 27|   _intro {
"_intro" is invalid, use "from" or "to"
```

Code example:

```
@-skrollr-keyframes intro
    _intro
        opacity:0;
        transform:translateY(0px);
    _introend
        opacity:1;
        transform:translateY(100px);
```

It makes sense that stylus sees "_intro" as an invalid property but I haven't found a way to bypass this.

I know this isn't supported out of the box, but maybe somebody have a solution?

**Comment by Prinzhorn** [comment]
I've never used stylus. This is the first thing I clicked on on the website, does it help? http://learnboost.github.io/stylus/docs/literal.html

**Comment by madsviktor** [comment]
@Prinzhorn Thanks, I'll try that. Right now I've changed the Stylus parser to allow all strings as animation input (not just from and to). If other people have the same problem: In parser.js I've changed "default:" in the switch-statement on line 773 to "break" instad of throwing an error. It's a hack but it works.

I'll try out your method and reply wether it works or not :)

**Comment by Prinzhorn** [comment]
> I'll try out your method and reply wether it works or not :)

Did you?

Feel free to reopen with new information.
