### ISSUE TITLE
ForceHeight:false messing up with Google Chrome

### ISSUE THREAD

**Issue by ghost** [Prinzhorn/skrollr-stylesheets#4]
I'm using relative mode for scrolling parallax effect. I've series of fixed height divs linedup one after each other. If i don't use forceHeight, after the last div, a large blank gap appears. When i use ForceHeight:false, it works fine in Firefox as it kill the gap after the last slide but Google Chrome  simply hide the last div and also 2nd live div get half cut.

**Comment by Prinzhorn** [comment]
This doesn't sound like it's a problem with skrollr-stylesheets.

Which skrollr version are you using?

**Comment by ghost** [comment]
I'm using skrollr v0.5.14. Here is the demo for your reference http://demos.aandesigners.com/sarralle/jsfiddle/skroll.html. Checkout out in Firefox and Chrome

**Comment by Prinzhorn** [comment]
Which Chrome version and OS? I don't see a gap on Ubuntu 12.10 with Chrome 25.0.1364.97

And please include the non-minified version of skrollr. This way I can easily debug it.

**Comment by ghost** [comment]
I'm on Mac with Chrome Version is Version 25.0.1364.99. I comment out
ForceHeight:false, now see the result in Chrom
http://demos.aandesigners.com/sarralle/jsfiddle/skroll.html

I've attached snapshot for your reference.[image: Inline image 1]

**Comment by ghost** [comment]
I've created two versions for you.

_Version 1: ForceHeight comment out._ (
http://demos.aandesigners.com/sarralle/jsfiddle/skroll.html)
Firefox Result: Huge gap in the end
Chrome Result: same as above

_Version 2: ForceHeight:false._ (
http://demos.aandesigners.com/sarralle/jsfiddle/skroll1.html)
Firefox Result: No gap and working fine
Chrome Result: Page Scrolling freeze. Half of slide 2 is visible while
third is completely hidden.

**Comment by Prinzhorn** [comment]
Thanks. Now I see the gap.

I don't have time to take a closer look. My first guess is that it was introduced by https://github.com/Prinzhorn/skrollr/commit/e7e7c55207301bf299e6e5d29b9cdacffb342a17

Please try with 0.5.12. If it works, then we have a good point to start.

Link to 0.5.12 https://github.com/Prinzhorn/skrollr/tree/586294290109d11aaafe53e3ccdc32f365a2879e

**Comment by Prinzhorn** [comment]
I moved this to the skrollr repo https://github.com/Prinzhorn/skrollr/issues/156

**Comment by Prinzhorn** [comment]
Could you please comment on https://github.com/Prinzhorn/skrollr/issues/156 (not here) if this is still an issue? Thanks!
