### ISSUE TITLE
CSS Selector Specificity Support (Override Previous Animation Definitions)

### ISSUE THREAD

**Issue by purefusion** [Prinzhorn/skrollr-stylesheets#40]
When defining animations using Skrollr Stylesheets, it appears as though animations defined for an element targeted with a CSS selector of lower specificity are not overriden by animations defined for the same element targeted with a higher specificity. 

Example:

<pre><code>
#header {
  -skrollr-animation-name:header;
}
@-skrollr-keyframes header {
  0  { height: 250px;} 
  1000 { height: 80px; }
  1001 { background-color: rgba(0,0,0,0); }
  2000 { background-color: rgba(0,0,0,.8); }
}
#header.alt {
  -skrollr-animation-name:header-alt;
}
@-skrollr-keyframes header-alt {
  0  { height: 250px;} 
  1000 { height: 80px; }
  1001 { background-color: rgba(255,255,255,0); }
  2000 { background-color: rgba(255,255,255,.8); }
}
</code>
</pre>

With the above in my Skrollr stylesheet, the 'header-alt' animation doesn't override the 'header' animation when the #header.alt class is used, as should be the case if native CSS specificity. I would prefer not to have to use two separate classes to control this animation if I don't have to.

**Comment by Prinzhorn** [comment]
Selector specificity is out of scope due to the complexity involved. This is also documented here https://github.com/Prinzhorn/skrollr-stylesheets#limitations

**Comment by purefusion** [comment]
For anyone looking for a workaround, I just placed the classed version before the non-classed version. However, your mileage may vary, as this workaround may not work in more extreme cases where multiple CSS specificities are used to target a single element or a range of elements, or instances where the elements' class may change dynamically.
