### ISSUE TITLE
SCSS, Skrollr & Colors

### ISSUE THREAD

**Issue by christoshrousis** [Prinzhorn/skrollr-stylesheets#42]
I'm not 100% sure about this, but I'm having trouble identifying whether this is skrollr stylesheets or scss.

In my stylesheet, colors with hex values that have numbers in them don't get converted to a proper hex?

In console, I get the error:
Uncaught Can't interpolate between "black" and "#{?}bbf{?}c" 

And when I view the source, the HTML inspector reports the correct hex.
(This gives me the impression that for some reason the skrollr plugin then reads over the HTML and fails to read it correctly, but how can this be?)

In the same page I have background color animated on scroll, but I've written it directly into the html.

**Comment by christoshrousis** [comment]
Was able to recreate on a colleges machine, and he was using color plugin, but was producing different results for different browsers. (for example HSLA was being used in chrome, something else in firefox producing 2 different results) both using macs.

**Comment by Prinzhorn** [comment]
> I'm having trouble identifying whether this is skrollr stylesheets or scss.

neither.

Quoting https://github.com/Prinzhorn/skrollr#limitations

> Color animations don't support named values like "red" or hex values like "#ff0000". Instead, you have to use rgb(), rgba(), hsl() and hsla(). Don't worry, there's a skrollr plugin for IE < 9 to support hsl() (without "a"!) and to fall rgba back to rgb.

**Comment by christoshrousis** [comment]
I think I missed something in my description, I WAS using rgb() I wasn't using named values, then something was converting my rgb's to named values, which skollr doesn't support.

**Comment by Prinzhorn** [comment]
https://github.com/Prinzhorn/skrollr-stylesheets/issues/11
