### ISSUE TITLE
Skrollr stylesheets with wordpress not working

### ISSUE THREAD

**Issue by EvilDonkeyLondon** [Prinzhorn/skrollr-stylesheets#45]
Skrollr works fine when implemented inline but it doesn't work with stylesheets. What am I doing wrong?

I have the stylesheet in an external link

<link rel="stylesheet" type="text/css" href="<?php echo get_template_directory_uri(); ?>/css/skrollr.css" media="only screen and (min-width: 992px)" data-skrollr-stylesheet />

Its content is

.page-id-5,
.page-id-5 .grey-mask {
    -skrollr-animation-name:bganimation;
}

@-skrollr-keyframes bganimation {
    0% {
        left:0;
    }

```
100% {
    left:10;
}

200% {
    left:80;
}

300% {
    left:100;
}
```

}

And initialized Skrollr Stylesheets at the bottom of the page before Skrollr itself. Tested it locally and online and still not working. Has it got any issues working with Wordpress? I don't get any error in the console.

Please help, thank you

**Comment by Prinzhorn** [comment]
There shouldn't be any problems with any CMS. Without posting a link to your website I can't help you any further.
