### ISSUE TITLE
Processing by node

### ISSUE THREAD

**Issue by TrySound** [Prinzhorn/skrollr-stylesheets#48]
I am excited by node.js and gulp in Front-end. And build all my projects with it. When I need some tool I create it.
So, maybe we will create a module for compiling `['*.skrollr.css', '*.skrollr.scss']` and merging with `html`?

**Comment by Prinzhorn** [comment]
I don't really see a use-case. This would only make sense for static websites but I'd say most of the sites are serves dynamically via some CMS.

**Comment by TrySound** [comment]
I build just static sites without any CMS, There are many.
And precompiling always faster then run-time.
