### ISSUE TITLE
IE 8

### ISSUE THREAD

**Issue by Prinzhorn** [Prinzhorn/skrollr-stylesheets#5]
http://stackoverflow.com/questions/15938690/skrollr-style-sheets-not-working-in-ie

**Comment by SILENTRUN** [comment]
I'll just add to this since I originally brought it up on stackoverflow. Skrollr style sheets are not writing the data attributes to the respective divs based off of the skrollr style sheet in IE 7 - IE 10. This is true for both <style> and <link>. Works great in Firefox, Chrome, and Safari.

**Comment by Prinzhorn** [comment]
Then please run these tests in IE (just open the link) https://dl.dropboxusercontent.com/u/37892603/skrollr-stylesheets/test/index.html

And paste it here or make a screenshot.

My Windows VM does not work atm.

IE 7 won't be supported though.

**Comment by Prinzhorn** [comment]
I've fired up a Windows VM with IE 8 and I'll try to fix the IE issues.

**Comment by Prinzhorn** [comment]
The tests are now passing it IE 8. Please grab the latest version and make sure to read the changelog! https://github.com/Prinzhorn/skrollr-stylesheets#002
