### ISSUE TITLE
CSS comments cause errors

### ISSUE THREAD

**Issue by cokeperez** [Prinzhorn/skrollr-stylesheets#50]
If you use /\* css comments */ an error is displayed. Skrollr works without problem.

**Uncaught SyntaxError: Failed to execute 'querySelectorAll' on 'Document': '/*.contact ' is not a valid selector**

**Comment by Prinzhorn** [comment]
> When I say "parsing" I mean it's using regular expressions. Thus you should avoid doing funky stuff inside your CSS files (actually, comments at the wrong place could break the current version). Just put all skrollr related things in one file and keep it clean.

https://github.com/Prinzhorn/skrollr-stylesheets#documentation

**Comment by cokeperez** [comment]
Sorry @Prinzhorn. I hadn't read the complete documentation.
