### ISSUE TITLE
Squarespace Compatibility

### ISSUE THREAD

**Issue by dom1080** [Prinzhorn/skrollr-stylesheets#53]
Unfortunately I don't seem to be able to get squarespace to function with stylesheets - have you heard of anyone else having any issues?

I've tried to implement it on this page, you can see the red element has been colored by skrollr with internal data tags. 

http://www.lovebournemouth.co.uk/bike-routess

The div below is the div i'm trying to use with stylesheets; with the following css copied from the github example and modified slightly : 

.tester {
-skrollr-webkit-animation-name:animation1;}
@-skrollr-webkit-keyframes animation1 {
    0 {        background:red!important;    }
    2000 {        background:transparent!important;    }
  /_Same as_/
    skrollr-2000 {        background:transparent!important;    }
} 

The .js file is recalled up like so 

< script src="/assets/skrollr-stylesheet.js"></script>
< link rel="stylesheet" type="text/css" href="/assets/skollr.css" data-skrollr-stylesheet>. 

Sorry to bother you but this script would be massively useful for my website and after triple checking that I didn't think I was inputting anything wrong (I'd be ecstatic to be proved otherwise) I've run out of options so thought I'd see if you might be able to help.

Cheers

**Comment by Prinzhorn** [comment]
Fix this first

> Uncaught ReferenceError: skrollrInit is not defined

**Comment by Prinzhorn** [comment]
Also the order is wrong with these

```
<script src="/assets/skrollr-stylesheet.js"></script>
<link rel="stylesheet" type="text/css" href="/assets/skollr.css" data-skrollr-stylesheet>
```

> In order to use skrollr-stylesheets, just place dist/skrollr.stylesheets.min.js at the bottom of your page before the closing </body> (but before skrollr itself). skrollr-stylesheets will execute right when it's included and searches for all stylesheets and processes them synchronously.

https://github.com/Prinzhorn/skrollr-stylesheets#the-script

**Comment by evolve2k** [comment]
Just reading through the issues, I reckon this sounds completed.
Suggest close.

**Comment by dom1080** [comment]
Apologies - I had github set up with an old address and had stopped checking back so hadn't seen this had been replied too. Thank for the reply and the great script Prinzhorn. Closed.
