### ISSUE TITLE
skrollr-stylesheets

### ISSUE THREAD

**Issue by kuraldesign** [Prinzhorn/skrollr-stylesheets#54]
Hi,

I'm having the toughest time trying to get the skrollr-stylesheets to execute in wordpress. It works perfectly for my site http://kuraldesign.com but the header and the logo doesn't shrink for my blog http://kuraldesign.com/blog/. I'm getting SyntaxError: DOM Exception 12: An invalid or illegal string was specified when I use the inspector. I'm confident it has to do with the way that I'm using it. Can you help? Thanks! Karl

**Comment by Prinzhorn** [comment]
> When I say "parsing" I mean it's using regular expressions. Thus you should avoid doing funky stuff inside your CSS files (actually, comments at the wrong place could break the current version). Just put all skrollr related things in one file and keep it clean.

https://github.com/Prinzhorn/skrollr-stylesheets#documentation

**Comment by kuraldesign** [comment]
Thanks. It works!
