### ISSUE TITLE
Plugin not Working

### ISSUE THREAD

**Issue by dflourusso** [Prinzhorn/skrollr-stylesheets#55]
See the description here: http://pt.stackoverflow.com/questions/63990/skroll-stylesheet-n%C3%A3o-funcionando

**Comment by Prinzhorn** [comment]
Can you post a link to the website?

**Comment by dflourusso** [comment]
http://www.paliari.com.br/

**Comment by Prinzhorn** [comment]
I don't see skrollr-stylesheets being used there.

Make sure to follow the instructions

> In order to use skrollr-stylesheets, just place dist/skrollr.stylesheets.min.js **at the bottom of your page** before the closing </body> (but before skrollr itself). skrollr-stylesheets will execute right when it's included and searches for all stylesheets and processes them synchronously.

https://github.com/Prinzhorn/skrollr-stylesheets#the-script
