### ISSUE TITLE
Not reading <link> stylesheet

### ISSUE THREAD

**Issue by SILENTRUN** [Prinzhorn/skrollr-stylesheets#8]
So skrollr stylesheets is now working great in IE 8+, Chrome, Firefox, and Safari, but only if the styles are included in a style tag on the page. External link stylesheets don't seem to be recognized and the data attributes are not being written to the respective divs.

**Comment by Prinzhorn** [comment]
Did you add the `data-skrollr-stylesheet` attribute?

**Comment by SILENTRUN** [comment]
Ah, my apologies. I didn't read that the logic changed. Really like that you changed it to tag them to include as opposed to dis-clued. All is working now.

**Comment by Prinzhorn** [comment]
> Really like that you changed it to tag them to include as opposed to dis-clued. All is working now.

Great ;-)
