### ISSUE TITLE
Question about animating

### ISSUE THREAD

**Issue by scgrossman** [Prinzhorn/skrollr-stylesheets#9]
I've got the data attributes being attached correctly, but when I scroll the values are aren't animating. I get an 'Unknown property' warning in Chrome Dev tools when inspecting "skrollr-animation-name", but that seems to get flagged in the test file as well.

**Comment by Prinzhorn** [comment]
> I get an 'Unknown property' warning in Chrome Dev tools when inspecting "skrollr-animation-name", but that seems to get flagged in the test file as well.

Yeah, because it's not a CSS property. Just ignore it.

You need to show your HTML. I can't guess why it's not working for you. If the data-attributes are attached, then it's not a problem with skrollr-stylesheets, because that's all it does.

**Comment by scgrossman** [comment]
Thanks for the reply, I must be missing something, here's the HTML :http://bit.ly/14bLp77

Is there some logic from the original skrollr library that needs to transferred in order
to animate the elements when scrolling?

**Comment by Prinzhorn** [comment]
You need skrollr itself. I thought this was clear. All skrollr-stylesheet does is adding the data-attributes. It just allows separation of the keyframes from the HTML document itself. After skrollr-stylesheet did it's job, your on the same step you were if you added them manually.

**Comment by scgrossman** [comment]
I figured as much, it's just this threw me for a loop:
"This is a completely separate project. skrollr-stylesheets does not depend on skrollr in any way".

Thanks for the clarification and your great work

**Comment by Prinzhorn** [comment]
What this quote means is that skrollr-stylesheets does it's job perfectly well without skrollr.

I'll leave this open to remind mind to update the README
